version: '3'
services:
  nextjs:
    build: ./
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/daydule/
    ports:
      - '3001:3001'
    command: 'npm run dev'
